Ho aggiunto es1.2
LorenzoDomina/esercizi_cpp pull request #3
Opened 2023-06-21 14:39 UTC by LorenzoDomina

Add es1.2

2023-06-21 15:46 UTC, giannivalenti requested changes
I would suggest some changes:
- please format the code using an automatic formatter (with VSCode you can format the opened document with `Shift` + `Alt` + `F`),
- please alwasy use english in your code (`scelta` => `choice`) &mdash; this comment doesn't apply to user messages,
- please add some comments that help the reader to understand your code, you should put each comment in a separate line, ideally just before the code line it refers to.

2023-06-21 15:46 UTC, giannivalenti commented on cpp/es1.2/es2_day1.cpp
> +    int n;
You could move this variable declaration inside the `do`-`while` loop, actually inside the `if (scelta == 1)` block: you don't need it anymore once you pushed it back into the vector.

2023-06-22 08:00 UTC, lucaotta commented on cpp/es1.2/es2_day1.cpp
> +    if(!v.empty()) {
Hai fatto bene a controllare la condizione di array vuoto!

2023-06-23 10:04 UTC, giannivalenti approved these changes

2023-06-23 10:04 UTC, giannivalenti commented
@lucaotta , per me questa PR va bene. Ti lascio la parola.

2023-06-23 11:03 UTC, lucaotta approved these changes
@LorenzoDomina per me ok, vai di merge! :rocket:

2023-06-23 12:14 UTC, merged