Bar v
LorenzoDomina/esercizi_cpp pull request #7
Opened 2023-07-03 14:54 UTC by LorenzoDomina

add esBar

2023-07-04 12:37 UTC, giannivalenti requested changes
Un ultimo commento finale: non hai committato il file `main.cpp`. Il progetto non compila. Puoi rimediare?

2023-07-04 12:37 UTC, giannivalenti commented on qml/barV/BarV/Bars.qml
> +    Repeater {
Ottima idea usare un `Repeater`! 👍

2023-07-04 12:37 UTC, giannivalenti commented on qml/barV/BarV/Bars.qml
> +        property var percentages: [Math.random(), Math.random(), Math.random(
Tre osservazioni su questa proprietà:
- Potrebbe stare nel componente principale (cioè la `Column`).
- Dovrebbe essere inizializzata con `[0, 0, 0, 0, 0]`, oppure con dei valori tra 0 e 1.
- Non è mai utilizzata... 🤔 Ma a questo rimedieremo presto.

2023-07-04 12:37 UTC, giannivalenti commented on qml/barV/BarV/Bars.qml
> +            }
Non c'è bisogno di tutto questo: il componente `Bar` ha già una proprietà che si chiama `percentage`. Puoi assegnarla direttamente così:

```Qml
        delegate: Bar {
            width: parent.width
            height: 40
            percentage: percentages[index]
        }
```

Questo funziona perché quando utilizzi un `Repeater` passando un numero come `model` (in realtà a `model` potresti passare anche altre cose di cui qui non parleremo), la variabile `index` contiene l'indice dell'elemento corrente. In questo caso la possiamo usare per accedere l'elemento i-esimo dell'array.

Puoi togliere sia la proprietà `currentPercentage` che l'handler `onCurrentPercentageChanged`.

2023-07-04 12:37 UTC, giannivalenti commented on qml/barV/BarV/Bars.qml
> +            }
Per quanto riguarda il `Timer`, potresti metterlo fuori, all'interno della `Column`, così ne instanzieresti uno solo.

Se ne instanzi uno solo, a quel punto il suo metodo `onTriggered` potrebbe generare un nuovo array, qualcosa tipo:
```
                onTriggered: {
                    percentages = [
                        // Qui metti quello che vuoi.
                        // Probabilmente cinque `Math.random()` tra 0 e 1...
                    ]
                }
```

Quando la proprietà `percentages` viene aggiornata, tutte le `Bar` se ne accorgono e si aggiornano di conseguenza.

2023-07-04 14:58 UTC, LorenzoDomina commented
Non so se ho capito bene le modifiche, comunque mi sono dimenticato di effettuare i commit viavia, scusate

2023-07-05 12:58 UTC, giannivalenti requested changes
@LorenzoDomina, ho visto che hai aggiunto un commit, però in quel commit hai solo aggiunto il file `main.cpp`. Per inviare anche le modifiche che hai fatto sugli altri file devi fare prima `git add` sui file modificati e poi fare un altro commit (e un altro push).

2023-07-07 09:58 UTC, lucaotta approved these changes
@LorenzoDomina togliamo la property `percentages` da Bars.qml e siamo a posto

2023-07-07 09:58 UTC, lucaotta commented on qml/barV/BarV/Bars.qml
> +        property var percentages: [Math.random(), Math.random(), Math.random(
Io toglierei questa property e basta. Poi per me possiamo mergiare

2023-07-07 10:48 UTC, merged